source "https://rubygems.org"

# new friends
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"

# old friends
gem "require_all"
gem "sqlite3"
gem "pry"

# to make API requests
gem 'rest-client'

# to prettify-CLI
gem 'tty-prompt', '~> 0.22.0'
gem 'artii', '~> 2.1', '>= 2.1.2'